[package]
name = "KanariSystem"
version = "0.1.0"
edition = "legacy"


[dependencies]
KanariFramework = { local = "../../framework/packages/kanari-framework" }
MoveStdlib = { local = "../../framework/packages/move-stdlib" }


[addresses]
kanari_system = "0x3"

