[package]
name = "kari-move-analyzer"
version = "1.0.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "A language server for Move"
repository = "https://github.com/move-language/move"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.95"
codespan-reporting = "0.11.1"
derivative = "2.2.0"
dunce = "1.0.5"
im = "15.1.0"
lsp-server = "0.5.1"
lsp-types = "0.90.1"
petgraph = "0.7.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
tempfile = "3.17.1"
url = "2.5.4"
clap = { version = "3.1.8", features = ["derive"] }
crossbeam = "0.8.4"
move-command-line-common.workspace = true
move-compiler.workspace = true
move-ir-types.workspace = true
move-package.workspace = true
move-symbol-pool.workspace = true

[features]
address20 = ["move-compiler/address20"]
address32 = ["move-compiler/address32"]
